/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yt.otter.canal.protocol.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ColumnContent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8912560515885191357L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ColumnContent\",\"namespace\":\"com.yt.otter.canal.protocol.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"isKey\",\"type\":\"boolean\"},{\"name\":\"isNull\",\"type\":\"boolean\"},{\"name\":\"value\",\"type\":\"string\"},{\"name\":\"mysqlType\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public boolean isKey;
  @Deprecated public boolean isNull;
  @Deprecated public java.lang.CharSequence value;
  @Deprecated public java.lang.CharSequence mysqlType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ColumnContent() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param isKey The new value for isKey
   * @param isNull The new value for isNull
   * @param value The new value for value
   * @param mysqlType The new value for mysqlType
   */
  public ColumnContent(java.lang.CharSequence name, java.lang.Boolean isKey, java.lang.Boolean isNull, java.lang.CharSequence value, java.lang.CharSequence mysqlType) {
    this.name = name;
    this.isKey = isKey;
    this.isNull = isNull;
    this.value = value;
    this.mysqlType = mysqlType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return isKey;
    case 2: return isNull;
    case 3: return value;
    case 4: return mysqlType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: isKey = (java.lang.Boolean)value$; break;
    case 2: isNull = (java.lang.Boolean)value$; break;
    case 3: value = (java.lang.CharSequence)value$; break;
    case 4: mysqlType = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'isKey' field.
   * @return The value of the 'isKey' field.
   */
  public java.lang.Boolean getIsKey() {
    return isKey;
  }

  /**
   * Sets the value of the 'isKey' field.
   * @param value the value to set.
   */
  public void setIsKey(java.lang.Boolean value) {
    this.isKey = value;
  }

  /**
   * Gets the value of the 'isNull' field.
   * @return The value of the 'isNull' field.
   */
  public java.lang.Boolean getIsNull() {
    return isNull;
  }

  /**
   * Sets the value of the 'isNull' field.
   * @param value the value to set.
   */
  public void setIsNull(java.lang.Boolean value) {
    this.isNull = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'mysqlType' field.
   * @return The value of the 'mysqlType' field.
   */
  public java.lang.CharSequence getMysqlType() {
    return mysqlType;
  }

  /**
   * Sets the value of the 'mysqlType' field.
   * @param value the value to set.
   */
  public void setMysqlType(java.lang.CharSequence value) {
    this.mysqlType = value;
  }

  /**
   * Creates a new ColumnContent RecordBuilder.
   * @return A new ColumnContent RecordBuilder
   */
  public static com.yt.otter.canal.protocol.avro.ColumnContent.Builder newBuilder() {
    return new com.yt.otter.canal.protocol.avro.ColumnContent.Builder();
  }

  /**
   * Creates a new ColumnContent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ColumnContent RecordBuilder
   */
  public static com.yt.otter.canal.protocol.avro.ColumnContent.Builder newBuilder(com.yt.otter.canal.protocol.avro.ColumnContent.Builder other) {
    return new com.yt.otter.canal.protocol.avro.ColumnContent.Builder(other);
  }

  /**
   * Creates a new ColumnContent RecordBuilder by copying an existing ColumnContent instance.
   * @param other The existing instance to copy.
   * @return A new ColumnContent RecordBuilder
   */
  public static com.yt.otter.canal.protocol.avro.ColumnContent.Builder newBuilder(com.yt.otter.canal.protocol.avro.ColumnContent other) {
    return new com.yt.otter.canal.protocol.avro.ColumnContent.Builder(other);
  }

  /**
   * RecordBuilder for ColumnContent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ColumnContent>
    implements org.apache.avro.data.RecordBuilder<ColumnContent> {

    private java.lang.CharSequence name;
    private boolean isKey;
    private boolean isNull;
    private java.lang.CharSequence value;
    private java.lang.CharSequence mysqlType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yt.otter.canal.protocol.avro.ColumnContent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isKey)) {
        this.isKey = data().deepCopy(fields()[1].schema(), other.isKey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isNull)) {
        this.isNull = data().deepCopy(fields()[2].schema(), other.isNull);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mysqlType)) {
        this.mysqlType = data().deepCopy(fields()[4].schema(), other.mysqlType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ColumnContent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yt.otter.canal.protocol.avro.ColumnContent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isKey)) {
        this.isKey = data().deepCopy(fields()[1].schema(), other.isKey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isNull)) {
        this.isNull = data().deepCopy(fields()[2].schema(), other.isNull);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mysqlType)) {
        this.mysqlType = data().deepCopy(fields()[4].schema(), other.mysqlType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isKey' field.
      * @return The value.
      */
    public java.lang.Boolean getIsKey() {
      return isKey;
    }

    /**
      * Sets the value of the 'isKey' field.
      * @param value The value of 'isKey'.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder setIsKey(boolean value) {
      validate(fields()[1], value);
      this.isKey = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isKey' field has been set.
      * @return True if the 'isKey' field has been set, false otherwise.
      */
    public boolean hasIsKey() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isKey' field.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder clearIsKey() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'isNull' field.
      * @return The value.
      */
    public java.lang.Boolean getIsNull() {
      return isNull;
    }

    /**
      * Sets the value of the 'isNull' field.
      * @param value The value of 'isNull'.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder setIsNull(boolean value) {
      validate(fields()[2], value);
      this.isNull = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'isNull' field has been set.
      * @return True if the 'isNull' field has been set, false otherwise.
      */
    public boolean hasIsNull() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'isNull' field.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder clearIsNull() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder clearValue() {
      value = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'mysqlType' field.
      * @return The value.
      */
    public java.lang.CharSequence getMysqlType() {
      return mysqlType;
    }

    /**
      * Sets the value of the 'mysqlType' field.
      * @param value The value of 'mysqlType'.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder setMysqlType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.mysqlType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'mysqlType' field has been set.
      * @return True if the 'mysqlType' field has been set, false otherwise.
      */
    public boolean hasMysqlType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'mysqlType' field.
      * @return This builder.
      */
    public com.yt.otter.canal.protocol.avro.ColumnContent.Builder clearMysqlType() {
      mysqlType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public ColumnContent build() {
      try {
        ColumnContent record = new ColumnContent();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.isKey = fieldSetFlags()[1] ? this.isKey : (java.lang.Boolean) defaultValue(fields()[1]);
        record.isNull = fieldSetFlags()[2] ? this.isNull : (java.lang.Boolean) defaultValue(fields()[2]);
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.mysqlType = fieldSetFlags()[4] ? this.mysqlType : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
